# Generated by Django 2.2 on 2019-12-14 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_matches', models.IntegerField(blank=True, null=True)),
                ('trophy', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('matches_played', models.IntegerField()),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='team.Championship')),
            ],
        ),
    ]
